name: ğŸ Generate Snake Contribution Graph

on:
  schedule:
    - cron: '0 */12 * * *' # Executa a cada 12 horas
  workflow_dispatch:

jobs:
  generate-snake:
    name: ğŸ Generate & Deploy Snake Animation
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ“¥ Checkout repository
        uses: actions/checkout@v3

      - name: ğŸ Generate snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: IanDinizFK
          outputs: |
            dist/github-contribution-grid-snake.svg

      - name: ğŸš€ Deploy snake to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: output
          publish_dir: ./dist
